macro(add_boost) # usage: add_boost(component1 component2...)
  if (CTHYB_BUILD_STATIC)
    set(Boost_USE_STATIC_LIBS        ON)
  endif()
  if (CTHYB_BUILD_SHARED)
    set(Boost_USE_STATIC_LIBS        OFF)
  endif()
  find_package (Boost 1.54.0 COMPONENTS ${ARGV} REQUIRED)
  #message(STATUS "Boost includes: ${Boost_INCLUDE_DIRS}" )
  #message(STATUS "Boost libs: ${Boost_LIBRARIES}" )
  #target_include_directories(${PROJECT_NAME} SYSTEM PUBLIC ${Boost_INCLUDE_DIRS})
  #target_link_libraries(${PROJECT_NAME} PUBLIC ${Boost_LIBRARIES})
endmacro(add_boost)
